hunav_loader:
  ros__parameters:
    map: map_social_scenarios
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
      - agent10
    agent1:
      id: 1
      skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -7.0
        y: 9.0
        z: 1.250000
        h: 0.0 #-1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 7.0
        y: 9.0
        z: 1.250000
      g1:
        x: -7.0
        y: 9.0
        z: 1.250000
    agent2:
      id: 2
      skin: 1
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -7.0
        y: 4.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 7.0
        y: 4.0
        z: 1.250000
      g1:
        x: -7.0
        y: 4.0
        z: 1.250000
    agent3:
      id: 3
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 7.0
        y: 7.0
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -7.0
        y: 7.0
        z: 1.250000
      g1:
        x: 7.0
        y: 7.0
        z: 1.250000
    agent4:
      id: 4
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 1.0
        y: -7.5
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -7.0
        y: -7.5
        z: 1.250000
      g1:
        x: 1.0
        y: -7.5
        z: 1.250000
    agent5:
      id: 5
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -5.0
        y: 5.0
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -5.0
        y: -1.0
        z: 1.250000
      g1:
        x: -5.0
        y: 5.0
        z: 1.250000
    agent6:
        id: 6
        skin: 1
        group_id: -1
        max_vel: 0.8
        radius: 0.4
        behavior: 
          type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
          configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
          duration: 40.0  # seg
          once: true
          vel: 0.4
          dist: 0.0
          goal_force_factor: 2.0
          obstacle_force_factor: 10.0
          social_force_factor: 5.0
          other_force_factor: 20.0
        init_pose:
          x: -3.0
          y: -1.0
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
        g0:
          x: -3.0
          y: 5.0
          z: 1.250000
        g1:
          x: -3.0
          y: -1.0
          z: 1.250000
    agent7:
      id: 7
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 2.0
        y: -4.0
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 2.0
        y: -8.0
        z: 1.250000
      g1:
        x: 2.0
        y: -4.0
        z: 1.250000
    agent8:
        id: 8
        skin: 4
        group_id: -1
        max_vel: 0.8
        radius: 0.4
        behavior: 
          type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
          configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
          duration: 40.0  # seg
          once: true
          vel: 0.4
          dist: 0.0
          goal_force_factor: 2.0
          obstacle_force_factor: 10.0
          social_force_factor: 5.0
          other_force_factor: 20.0
        init_pose:
          x: 3.0
          y: -1.0
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
        g0:
          x: 3.0
          y: 5.0
          z: 1.250000
        g1:
          x: 3.0
          y: -1.0
          z: 1.250000
    agent9:
      id: 9
      skin: 1
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 4.0
        y: 5.0
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 4.0
        y: -1.0
        z: 1.250000
      g1:
        x: 4.0
        y: 5.0
        z: 1.250000
    agent10:
      id: 10
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 7.0
        y: -6.0
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -7.0
        y: -6.0
        z: 1.250000
      g1:
        x: 7.0
        y: -6.0
        z: 1.250000
  