hunav_loader:
  ros__parameters:
    map: social_indoor
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
      - agent10
      - agent11
      - agent12
      - agent13
      - agent14
      - agent15
      - agent16
      - agent17
    agent1:
      id: 1
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 7.5
        y: 6.2
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 7.5
        y: 8.5
        z: 1.250000
      g1:
        x: 7.5
        y: 6.2
        z: 1.250000
    agent2:
      id: 2
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 7.5
        y: 5.8
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 7.5
        y: 3.5
        z: 1.250000
      g1:
        x: 7.5
        y: 5.8
        z: 1.250000
    agent3:
      id: 3
      skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 5.5
        y: 8.5
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 5.5
        y: 6.2
        z: 1.250000
      g1:
        x: 5.5
        y: 8.5
        z: 1.250000
    agent4:
      id: 4
      skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 5.5
        y: 3.5
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 5.5
        y: 5.8
        z: 1.250000
      g1:
        x: 5.5
        y: 3.5
        z: 1.250000
    agent5:
      id: 5
      skin: 1
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -1.4
        y: -9.0
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -2.4
        y: -9.0
        z: 1.250000
      g1:
        x: -1.4
        y: -9.0
        z: 1.250000
    agent6:
      id: 6
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -6.5
        y: 8.5
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -2.0
        y: 8.5
        z: 1.250000
      g1:
        x: -6.5
        y: 8.5
        z: 1.250000
    agent7:
      id: 7
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -8.2
        y: 0.65
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -9.2
        y: 4.15
        z: 1.250000
      g1:
        x: -8.2
        y: 7.0
        z: 1.250000
      g2:
        x: -8.2
        y: 0.65
        z: 1.250000
    agent8:
      id: 8
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -2.8
        y: 4.6
        z: 1.250000
        h: -2.8
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -3.0
        y: 4.5
        z: 1.250000
    agent9:
      id: 9
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -3.7
        y: 2.2
        z: 1.250000
        h: 2.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -3.65
        y: 2.3
        z: 1.250000
    agent10:
      id: 10
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -5.5
        y: 4.3
        z: 1.250000
        h: -0.75
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -5.6
        y: 4.25
        z: 1.250000
    agent11:
        id: 11
        skin: 3
        group_id: -1
        max_vel: 0.8
        radius: 0.4
        behavior: 
          type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
          configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
          duration: 40.0  # seg
          once: true
          vel: 0.4
          dist: 0.0
          goal_force_factor: 2.0
          obstacle_force_factor: 10.0
          social_force_factor: 5.0
          other_force_factor: 20.0
        init_pose:
          x: -7.8
          y: -8.65
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: -8.2
          y: -7.0
          z: 1.250000
        g1:
          x: -7.8
          y: -4.15
          z: 1.250000
        g2:
          x: -8.8
          y: -2.15
          z: 1.250000
        g3:
          x: -7.8
          y: -8.65
          z: 1.250000
    agent12:
        id: 12
        skin: 1
        group_id: -1
        max_vel: 0.8
        radius: 0.4
        behavior: 
          type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
          configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
          duration: 40.0  # seg
          once: true
          vel: 0.4
          dist: 0.0
          goal_force_factor: 2.0
          obstacle_force_factor: 10.0
          social_force_factor: 5.0
          other_force_factor: 20.0
        init_pose:
          x: 4.6
          y: 0.0
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: 4.0
          y: -7.8
          z: 1.250000
        g1:
          x: 8.3
          y: -6.0
          z: 1.250000
        g2:
          x: 2.2
          y: -3.3
          z: 1.250000
        g3:
          x: 4.6
          y: 0.0
          z: 1.250000
    agent13:
      id: 13
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 2.8
        y: -7.4
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 6.4
        y: -0.55
        z: 1.250000
      g1:
        x: 8.2
        y: -4.1
        z: 1.250000
      g2:
        x: 2.8
        y: -7.4
        z: 1.250000
    agent14:
        id: 14
        skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
        init_pose:
          x: 6.5
          y: -6.5
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: 2.45
          y: -1.15
          z: 1.250000
        g1:
          x: 7.17
          y: -2.55
          z: 1.250000
        g2:
          x: 2.86
          y: -5.84
          z: 1.250000
        g3:
          x: 6.5
          y: -6.5
          z: 1.250000
    agent15:
      id: 15
      skin: 1
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 6.78
        y: -2.86
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 4.0
        y: -0.35
        z: 1.250000
      g1:
        x: 4.0
        y: -7.1
        z: 1.250000
      g2:
        x: 6.78
        y: -2.86
        z: 1.250000
    agent16:
      id: 16
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 1.8
        y: -1.85
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 1.95
        y: -6.0
        z: 1.250000
      g1:
        x: 1.8
        y: -1.85
        z: 1.250000
    agent17:
      id: 17
      skin: 4
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 7.2
        y: 0.85
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 4.0
        y: 0.9
        z: 1.250000
      g1:
        x: 8.39
        y: -7.0
        z: 1.250000
      g2:
        x: 7.2
        y: 0.85
        z: 1.250000