hunav_loader:
  ros__parameters:
    map: social_nav_map2
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
      - agent10
      - agent11
      - agent12
    agent1:
      id: 1
      skin: 4
      behavior: 2
      group_id: -1
      max_vel: 0.35
      radius: 0.35
      init_pose:
        x: 3.8
        y: 8.15
        z: 1.250000
        h: -3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 8.7
        y: 8.15
        z: 1.250000
      g1:
        x: 3.8
        y: 8.15
        z: 1.250000
    agent2:
      id: 2
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.26
      radius: 0.4
      init_pose:
        x: 1.58
        y: 7.5
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 1.58
        y: 1.224
        z: 1.250000
      g1:
        x: 1.58
        y: 7.5
        z: 1.250000
    agent3:
      id: 3
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: 1.85
        y: -0.1
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 1.85
        y: -4.1
        z: 1.250000
      g1:
        x: 1.85
        y: -0.1
        z: 1.250000
    agent4:
      id: 4
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: 3.58
        y: -2.95
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 3.58
        y: 1.35
        z: 1.250000
      g1:
        x: 3.58
        y: -5.65
        z: 1.250000
    agent5:
      id: 5
      skin: 2
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 8.4
        y: 5.0
        z: 1.250000
        h: -2.9
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 5.9
        y: 4.3
        z: 1.250000
      g1:
        x: 8.4
        y: 5.0
        z: 1.250000
    agent6:
      id: 6
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 6.7
        y: 3.50
        z: 1.250000
        h: 1.68
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 6.65
        y: 3.50
        z: 1.250000
      g1:
        x: 6.7
        y: 3.55
        z: 1.250000
    agent7:
        id: 7
        skin: 2
        behavior: 2
        group_id: -1
        max_vel: 0.5
        radius: 0.4
        init_pose:
          x: 7.91
          y: -7.8
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: 6.15
          y: -7.74
          z: 1.250000
        g1:
          x: 7.91
          y: -7.8
          z: 1.250000
        g2:
          x: 7.92
          y: -5.38
          z: 1.250000
        g3:
          x: 7.91
          y: -7.8
          z: 1.250000
    agent8:
      id: 8
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.5
      radius: 0.4
      init_pose:
        x: 7.41
        y: -4.5
        z: 1.250000
        h: -3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 4.53
        y: -4.8
        z: 1.250000
      g1:
        x: 7.41
        y: -4.5
        z: 1.250000
    agent9:
      id: 9
      skin: 4
      behavior: 2
      group_id: -1
      max_vel: 0.3
      radius: 0.4
      init_pose:
        x: 5.9
        y: -0.06
        z: 1.250000
        h: 1.57
      goal_radius: 0.12
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 7.3
        y: -1.57
        z: 1.250000
      g1:
        x: 5.9
        y: -2.1
        z: 1.250000
      g2:
        x: 7.3
        y: -1.57
        z: 1.250000
      g3:
        x: 5.9
        y: -0.06
        z: 1.250000
    agent10:
      id: 10
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 6.862
        y: -6.0
        z: 1.250000
        h: 1.68
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 6.5
        y: -5.68
        z: 1.250000
      g1:
        x: 6.86
        y: -6.0
        z: 1.250000
    agent11:
      id: 11
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      init_pose:
        x: 3.0
        y: -5.5
        z: 1.250000
        h: 0.0
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 2.0
        y: -8.3
        z: 1.250000
      g1:
        x: 3.1
        y: -5.5
        z: 1.250000
    agent12:
      id: 12
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.25
      radius: 0.4
      init_pose:
        x: 7.65
        y: 0.5
        z: 1.250000
        h: 1.68
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 7.95
        y: -1.3
        z: 1.250000
      g1:
        x: 7.65
        y: 0.5
        z: 1.250000