hunav_loader:
  ros__parameters:
    map: social_small_map
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
      - agent10
      - agent11
    agent1:
      id: 1
      skin: 4
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 2.0
        y: 8.5
        z: 1.250000
        h: -1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 2.0
        y: 4.6
        z: 1.250000
      g1:
        x: 2.0
        y: 8.5
        z: 1.250000
    agent2:
      id: 2
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 2.3
        y: 2.5
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 2.3
        y: 2.51
        z: 1.250000
    agent3:
      id: 3
      skin: 3
      behavior: 1
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 7.38
        y: 7.1
        z: 1.250000
        h: 0.15
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 7.29
        y: 7.1
        z: 1.250000
    agent4:
      id: 4
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 5.1
        y: 6.4
        z: 1.250000
        h: 0.82
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 5.11
        y: 6.45
        z: 1.250000
    agent5:
      id: 5
      skin: 2
      behavior: 4
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 6.68
        y: 4.39
        z: 1.250000
        h: -2.75
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 6.7
        y: 4.4
        z: 1.250000
    agent6:
        id: 6
        skin: 1
        behavior: 1
        group_id: -1
        max_vel: 0.6
        radius: 0.4
        init_pose:
          x: 4.6
          y: 0.0
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: 2.0
          y: -7.8
          z: 1.250000
        g1:
          x: 8.3
          y: 1.0
          z: 1.250000
        g2:
          x: 7.2
          y: -3.3
          z: 1.250000
        g3:
          x: 4.6
          y: 0.0
          z: 1.250000
    agent7:
      id: 7
      skin: 2
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 2.8
        y: -7.4
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 6.4
        y: -0.55
        z: 1.250000
      g1:
        x: 8.2
        y: -4.1
        z: 1.250000
      g2:
        x: 5.2
        y: -3.1
        z: 1.250000
      g3:
        x: 2.8
        y: -7.4
        z: 1.250000
    agent8:
        id: 8
        skin: 4
        behavior: 3
        group_id: -1
        max_vel: 0.6
        radius: 0.4
        init_pose:
          x: 6.5
          y: -6.5
          z: 1.250000
          h: 1.57
        goal_radius: 0.3
        cyclic_goals: true
        goals:
          - g0
        g0:
          x: 6.51
          y: -6.5
          z: 1.250000
    agent9:
      id: 9
      skin: 1
      behavior: 1
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 6.78
        y: -2.86
        z: 1.250000
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 4.0
        y: -0.35
        z: 1.250000
      g1:
        x: 4.0
        y: -7.1
        z: 1.250000
      g2:
        x: 6.78
        y: -2.86
        z: 1.250000
    agent10:
      id: 10
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: 1.8
        y: -1.85
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 1.95
        y: -6.0
        z: 1.250000
      g1:
        x: 1.8
        y: -1.85
        z: 1.250000
    agent11:
      id: 11
      skin: 4
      behavior: 1
      group_id: -1
      max_vel: 0.7
      radius: 0.4
      init_pose:
        x: 8.2
        y: 0.85
        z: 1.250000
        h: 3.14
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 2.8
        y: 0.9
        z: 1.250000
      g1:
        x: 8.39
        y: -7.0
        z: 1.250000
      g2:
        x: 8.2
        y: 0.85
        z: 1.250000