hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
    agent1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -1.662851
        y: -4.881244
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -1.208216
        y: 7.755196
        h: 1.250000
      g1:
        x: -1.662851
        y: -4.881244
        h: 0.0
    agent2:
      id: 2
      skin: 2
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -1.942911
        y: -5.826442
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -1.768548
        y: 7.860263
        h: 1.250000
      g1:
        x: -1.942911
        y: -5.826442
        h: 0.0
    agent3:
      id: 3
      skin: 3
      group_id: -1
      max_vel: 0.8
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.4
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -2.538036
        y: -5.021280
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -2.048713
        y: 7.755195
        h: 1.250000
      g1:
        x: -2.538036
        y: -5.021280
        h: 0.0