hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
    agent1:
      id: 1
      skin: 0
      behavior: 1
      group_id: 1
      max_vel: 0.7
      radius: 0.4
      init_pose:
        x: -1.662851
        y: -5.881244
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -1.208216
        y: 8.755196
        h: 1.250000
    agent2:
      id: 2
      skin: 2
      behavior: 1
      group_id: 1
      max_vel: 0.7
      radius: 0.4
      init_pose:
        x: -1.942911
        y: -6.826442
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -1.768548
        y: 8.860263
        h: 1.250000
    agent3:
      id: 3
      skin: 3
      behavior: 1
      group_id: 1
      max_vel: 0.7
      radius: 0.4
      init_pose:
        x: -2.538036
        y: -6.021280
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: -2.048713
        y: 8.755195
        h: 1.250000