hunav_loader:
  ros__parameters:
    map: social_nav_map2
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
      - agent10
      - agent11
    agent1:
      id: 1
      skin: 4
      behavior: 2
      group_id: -1
      max_vel: 0.2
      radius: 0.35
      init_pose:
        x: -5.0
        y: 3.23
        z: 1.250000
        h: 0.0
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -0.40
        y: 3.23
        z: 1.250000
      g1:
        x: -5.0
        y: 3.23
        z: 1.250000
    agent2:
      id: 2
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: -3.0
        y: 4.1
        z: 1.250000
        h: 0.0
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 0.40
        y: 4.1
        z: 1.250000
      g1:
        x: -3.0
        y: 4.1
        z: 1.250000
    agent3:
      id: 3
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.3
      radius: 0.4
      init_pose:
        x: 0.598861
        y: -3.53
        z: 1.250000
        h: 1.57
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 0.598861
        y: 3.03
        z: 1.250000
      g1:
        x: 0.598861
        y: -3.53
        z: 1.250000
    agent4:
      id: 4
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: -4.909480
        y: -0.359162
        z: 1.250000
        h: 0.0
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -1.467240
        y: -0.359162
        z: 1.250000
      g1:
        x: -4.909480
        y: -0.359162
        z: 1.250000
    agent5:
      id: 5
      skin: 2
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: -1.467240
        y: -1.010809
        z: 1.250000
        h: -3.14
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -4.909480
        y: -1.010809
        z: 1.250000
      g1:
        x: -1.467240
        y: -1.010809
        z: 1.250000
    agent6:
      id: 6
      skin: 1
      behavior: 2
      group_id: -1
      max_vel: 0.6
      radius: 0.4
      init_pose:
        x: -1.949810
        y: -2.442120
        z: 1.250000
        h: 2.405869
      goal_radius: 0.1
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -5.025910
        y: 1.01350
        z: 1.250000
      g1:
        x: -1.949810
        y: -2.442120
        z: 1.250000
    agent7:
        id: 7
        skin: 2
        behavior: 2
        group_id: -1
        max_vel: 0.4
        radius: 0.4
        init_pose:
          x: 3.658020
          y: 1.545410
          z: 1.250000
          h: 0.0
        goal_radius: 0.15
        cyclic_goals: true
        goals:
          - g0
          - g1
          - g2
          - g3
        g0:
          x: 5.0
          y: 2.506170
          z: 1.250000
        g1:
          x: 3.486250
          y: 3.372910
          z: 1.250000
        g2:
          x: 5.0
          y: 2.506170
          z: 1.250000
        g3:
          x: 3.658020
          y: 1.545410
          z: 1.250000
    agent8:
      id: 8
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: 3.224787
        y: -0.90
        z: 1.250000
        h: 2.615592
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 2.302110
        y: 0.4120
        z: 1.250000
      g1:
        x: 3.258020
        y: 1.145410
        z: 1.250000
      g2:
        x: 2.302110
        y: 0.3120
        z: 1.250000
      g3:
        x: 3.224787
        y: -0.90
        z: 1.250000
    agent9:
      id: 9
      skin: 4
      behavior: 2
      group_id: -1
      max_vel: 0.5
      radius: 0.4
      init_pose:
        x: 2.53
        y: -4.0
        z: 1.250000
        h: 1.57
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 2.53
        y: -1.0
        z: 1.250000
      g1:
        x: 2.53
        y: -4.0
        z: 1.250000
    agent10:
      id: 10
      skin: 3
      behavior: 2
      group_id: -1
      max_vel: 0.1
      radius: 0.4
      init_pose:
        x: 3.755150
        y: -3.0
        z: 1.250000
        h: 1.57
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 3.78
        y: -3.0
        z: 1.250000
      g1:
        x: 3.755150
        y: -3.0
        z: 1.250000
    agent11:
      id: 11
      skin: 2
      behavior: 2
      group_id: -1
      max_vel: 0.4
      radius: 0.4
      init_pose:
        x: 4.9
        y: -2.0
        z: 1.250000
        h: -0.824005
      goal_radius: 0.15
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 3.3
        y: -2.0
        z: 1.250000
      g1:
        x: 4.9
        y: -2.0
        z: 1.250000
      