main_node:
  ros__parameters:
    # Robot parameters
    robot_name: "jackal_ugv"
    max_lin_vel: 0.8
    min_lin_vel: 0.05
    max_ang_vel: 2.0
    min_ang_vel: 0.05
    robot_type: "rectangular" # rectangular or circular
    robot_radius: 0.2 # [m], If robot_type is cicrular
    robot_size: [0.508, 0.430] # [m, m], Lenght, Width if robot_type is rectangular
    collision_tolerance: 0.000 # [m], tollerance of collision added to robot_radius or robot_size
    warning_tolerance: 0.1 # [m], warning window added to robot_radius or robot_size
    goal_tolerance: 0.40

    # World parameters
    world_name: "adaptive_test.world" #Leave empty to obtain no world
    data_path: "adaptive_test.json"
    collision_check: 0.36

    # Task parameters
    task: 'adaptive_nav'
    
    # Sensors parameters
    sensor: 'applr' # lidar or rgb_camera or depth_camera
    applr_param:
      update_frequency: 10.0 # update the controller parameters at this frequency
    visual_data: 'features'
    features: 12544
    channels: 1
    imu_enabled: "true"
    camera_enabled: "false"
    stereo_camera_enabled: "false"
    lidar_enabled: "true"
    sensors_topic:
      rgb_topic: "/camera/image_raw"
      depth_topic: "/camera/depth/image_raw"
      laser_topic: "/scan"
      imu_topic: "/imu/data"
      odom_topic: "/odom"
    laser_param:
      max_distance: 12.0 # Meters
      num_points: 36 # int divider of 360
    depth_param:
      dist_cutoff: 5 # Meters
      width: 112
      height: 112
      show_image: False
    rgb_param:
      width: 640
      height: 480
      show_image: False 

    # Metrics
    path_distance: False
    distance_path_ratio: True
    clearance_time: True
    velocity: True
    max_min_accelerations: True
    cumulative_heading_average: True
    obstacle_clereance: True
    controller_params: True
    following_heading_metrics: False
    wineyard_path_comparison: False
