main_node:
  ros__parameters:
    # Mode
    mode: "training" # Training or testing
    # Robot parameters
    robot_name: "jackal"
    max_lin_vel: 0.6
    min_lin_vel: 0.05
    max_ang_vel: 1.5
    min_ang_vel: 0.05
    robot_type: "rectangular" #"circular" # rectangular or circular
    robot_radius: 0.26 #0.2 # [m], If robot_type is circular
    robot_size: [0.508, 0.430] # [m, m], Lenght, Width if robot_type is rectangular
    collision_tolerance: 0.05 # [m], tollerance of collision added to robot_radius or robot_size
    warning_tolerance: 0.1 # [m], warning window added to robot_radius or robot_size
    goal_tolerance: 0.40

    # World parameters
    world_name: "social_nav.world" #Leave empty to obtain no world
    data_path: "social_nav.json"  #"social_indoor2.json"
    agents_config: "social_indoor_agents3.yaml" #"social_indoor2_agents.yaml"

    use_localization: False

    # Task parameters
    task: 'SocialForceWindow' # SocialForceWindow, SocialForceWindowCostmap, SocialController, SocialController
    # Sensors parameters
    sensor: 'applr' # lidar or rgb_camera or depth_camera
    update_frequency: 1.0 #20.0 # update the controller parameters at this frequency
    visual_data: 'features'
    features: 10000
    channels: 1
    imu_enabled: "false"
    camera_enabled: "false"
    stereo_camera_enabled: "false"
    lidar_enabled: "true"
    sensors_topic:
      rgb_topic: "/camera/image_raw"
      depth_topic: "/camera/depth/image_raw"
      laser_topic: "/front/scan"
      imu_topic: "/imu/data"
      odom_topic: "/jackal/odom"
    laser_param:
      max_distance: 3.0 # Meters
      total_points: 360  # --Noé. Number of total laser points (360 Husky, 618 Pmb2)
      num_points: 36 #36 # int divider of 360 (husky). Step size to skip laser points
    depth_param:
      dist_cutoff: 5.0 # Meters
      width: 112
      height: 112
      show_image: False
    rgb_param:
      width: 640
      height: 480
      show_image: False 
    costmap_param:
      width: 20 #100
      height: 20 #100
      show_image: False
