simulation_node:
  ros__parameters:
    models_path_gazebo: "/home/simone/.gazebo/models/vine_plant3/model.sdf"
    models_path_robot: "/home/simone/my_ws/src/ROS2Jackal/jackal_description/urdf/jackal.urdf.xacro"
    models_path_terrain: "/home/simone/.gazebo/models/real_terrain_with_gravel/model.sdf"
    terrain_flag: False
    min_num_rows: 2 #MUST NOT go under 2
    max_num_rows: 3
    min_row_yaw: 0.52 # In radians
    max_row_yaw: 2.10 # In radians
    intra_row_distance: 3.0
    plants_distance: 10.0
    max_number_plants_per_rows: 5
